package rich;

public enum Status {
    WAIT_RESPONSE,
    WAIT_BUY_RESPONSE,
    WAIT_BUILD_RESPONSE,
    WAIT_SELECT_GIFT_RESPONSE,
    WAIT_BUY_TOOL_RESPONSE,
    WAIT_USE_MAGIC_RESPONSE,
    END_TURN,
    WAIT_COMMAND,
    LOSE_GAME,
    WAIT_START,
    IN_PROGRESS,
    WAIT_INIT_BALANCE,
    WAIT_INIT_PLAYER,
    END_GAME
}
